matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: "3.5"

install:
  - python -m pip install --upgrade sphinx sphinx_rtd_theme

script:
  - python -m sphinx -W -a -E -b html -n docs docs/_build
